#define PROJ_SCREENMODE TASMODE

#define PROJ_FPS 255

#define PROJ_HIGH_RAM HIGH_ON
#define PROJ_ENABLE_SOUND 1
#define PROJ_MAX_SPRITES 128
#define PROJ_TILE_H 8
#define PROJ_TILE_W 8
#define PROJ_DEVELOPER_MODE 0
#define MAX_TILE_COUNT 256
